### ISSUE TITLE
Keyboard testing

### ISSUE THREAD

**Issue by AgentNemo** [bevzzz/audioslave#2]
One thing I noticed will trying to test the keyboard.go, you use the dependency also in the tests. 
Please mock the lib so the test can run.

**Comment by bevzzz** [comment]
I use `keyboard.KeyEvent` struct to imitate keystrokes in the tests (without _really_ using the package).  
It does bind my tests to the package though, so a way to solve it would be to use a channel of locally-defined structs, e.g `KeyPress`, which would "wrap" around the library's `keyboard.KeyEvent` in production and could be mocked in the tests.  

What I feel though is that:
1. The local struct would eventually need to re-use some of the types defined in the package (e.g. the [Key enum](https://github.com/eiannone/keyboard/blob/master/keyboard_common.go#L9))   
2. Without a clear use case (an alternative library that could be used) it feels like it would complicate things rather than make them clearer. But that's debatable.

@AgentNemo  do you think it's worth doing that refactoring now?
